### ISSUE TITLE
Is project still alive? What about migrate to Re#10 SDK?

### ISSUE THREAD

**Issue by mokeev1995** [JetBrains/FSharper#64]

**Comment by nesteruk** [comment]
It hasn't been given enough attention recently. Migrating to R#10 SDK should be easy, though.

**Comment by mokeev1995** [comment]
@nesteruk so I think it might be good idea to build it for latest R# and create Release on github with binaries or installer.

**Comment by nesteruk** [comment]
@mokeev1995 unfortunately there's nothing to release yet. need the mvp before posting it in binary form.

**Comment by mokeev1995** [comment]
it's sad that neither MSVS nor R# doesn't have good enough F# support...

**Comment by nesteruk** [comment]
@mokeev1995  you are most welcome to help us implement this

**Comment by rasch** [comment]
I started moving [towards R#10](https://github.com/rasch/FSharper/tree/ReSharper10) but I'm stuck with failing tests<sup>1</sup>. As I have no knowledge of R# plugin development yet it would be great if someone could give some guidance. I'll continue with below list...

**Debatable changes** (and motivation)
- changed to VS 2015 (I don't have older versions installed)
- set target to 4.5 (dev guide mentions 4.0 for 9.1 but some NuGet packages for 10.0 are >= 4.5)
- removed (empty) resources and settings (got assembly load failures as .NET was looking for resource dll)
- deactivated ICE validation (for now, see below)
- `TokenNodeType` now requires an index, which I set to obsolete DummyIndex = 0 where I couldn't pull a meaningful value.
- Installed SDK package for all projects, could probably be finer grained (convenience)

**TODO**
- [x] fix merge conflict residuals
- [x] SDK 10 NuGet packages (including nuget.config for tests)
- [x] \(ignorant) fixes for compile errors
- [ ] re-instantiate / fix tests
- [ ] use new TokenGen infrastructure
- [ ] fix MSB3270 build warnings (architecture mismatch)
- [ ] fix CS0618 (obsolete) warnings
- [ ] package for installation / update installer (if needed)
- [ ] update readme
- [ ] ...

<sup>1</sup>Cannot serve Settings Store Entry UseNUnit3 of type UseNUnit3 with property type UseNUnit3...

**Comment by nesteruk** [comment]
@rasch I'll ask my colleagues; meanwhile, try checking the NUnit version setting when executing test - who knows, there might be some mismatch.

**Comment by nesteruk** [comment]
@rasch I am told that a possible solution is to remove all the `*.sstg` files

**Comment by nesteruk** [comment]
@rasch apparently, this is an issue that has only been fixed in ReSharper 10.1

**Comment by rasch** [comment]
@nesteruk Thanks. Upgrading to 10.1 EAP 6 did fix the test issue. Now working on getting parser tests to work ([lexer's fine](https://github.com/rasch/FSharper/commit/87f4b4f4f17b382dea8688c8e4255fb4c105f822)).

**Comment by rasch** [comment]
It seems the parser tests were abandoned a long time ago and getting them to work again is beyond what I'd planned. Technically, I migrated the code to 10.1, so I'll raise a pull request.
For the time being I don't have the time to continue working on the "business code" though.

**Comment by citizenmatt** [comment]
Yeah, this project hasn't been touched for a couple of years, and isn't likely to be carried further in its current state. I think it might be worth removing it, to be honest.

**Comment by nesteruk** [comment]
Yes, realistically I think we won't carry this through to a variable
product. This kind of project necessitates a full-time commitment and I
guess all of us are far too busy with many other things.

On 28 March 2016 at 18:57, Matt Ellis <notifications@github.com> wrote:

> Yeah, this project hasn't been touched for a couple of years, and isn't
> likely to be carried further in its current state. I think it might be
> worth removing it, to be honest.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JetBrains/FSharper/issues/64#issuecomment-202456236>
>



-- 
Dmitri Nesteruk
dmitrinesteruk@gmail.com
skype: dmitri.nesteruk

**Comment by automagic** [comment]
Are you guys aware that your official support page references this (dead) project? https://resharper-support.jetbrains.com/hc/en-us/articles/206546389-Does-ReSharper-support-F-

kudos to @rasch for trying to get something going.

**Comment by nesteruk** [comment]
@automagic we are aware that support references this project, it was our intention to do so. as to whether this project lives or dies, this is up to the community
